config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.append do
    resources :call_messages, only: [:new, :create]
    get '/brands', :to =>'products#brand_index'
    get '/brands/:id', :to => 'products#brand_page'
    namespace :admin, path: Spree.admin_path do
      resources :call_messages
      resources :providers
    end
  end 
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/orders/remove_item" => "spree/orders#remove_line_item"
	get '*id', :to => 'spree/taxons#show', :as => :categories

  #resources :call_messages#, :only => [:create, :new]
end

app/views/spree/admin/products/_index_table.html.erb
<% collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <%= form_for [:admin, product], method: :put, html: { multipart: true, :remote => false } do |f| %>
              <td class="sku" ><%#= f.text_field :sku, size: 8, class: 'form-control', :value => product.sku %><%= product.sku%></td>
              <td class="status"><%= f.check_box :available_on, checked: product.available?, class: 'form-control' %> </td>
              <td class="image" ><%= mini_image product %></td>
              <td ><%= link_to truncate(product.try(:name), length: 80), edit_admin_product_path(product) %></td>
              <td class="text-center" ><%= f.text_field :price, value: product.price, class: 'form-control', disabled: (cannot? :update, product.price) %></td>
              <td >
                <%= f.select :provider_id, options_for_select(Spree::Provider.active_providers.map{|p| [p.name, p.id]}, product.provider_id), {include_blank: true}, {class: 'form-control'}%>
              </td>
              
              <td><%= f.text_field :provider_price, value: product.provider_price, class: 'form-control' %></td>       
              <td>
                <%= product.available_on.strftime("%d/%m/%Y   %T") if product.available?%>
                <%= f.check_box :from_index, class: 'form-control hidden', :hidden => true%>
              </td> 
              <td> <%= button Spree.t('actions.update'), 'refresh', 'submit', {class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %></td>
              
            <% end -%>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
                <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
                <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
                <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
<% end %>

app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Product) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_product), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_product' } %>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {f: f} %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, size: 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, size: 15, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="field checkbox">
            <label>
              <%= f.check_box :deleted_at_null, {checked: params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              <%= Spree.t(:show_deleted) %>
            </label>
          </div>

          <div class="field checkbox">
            <label>
              <%= f.check_box :not_discontinued, {checked: params[:q][:not_discontinued] == '0'}, '0', '1' %>
              <%= Spree.t(:show_discontinued ) %>
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 5%">
      <col style="width: 5%">
      <col style="width: 30%">
      <col style="width: 8%">
      <col style="width: 8%">
      <col style="width: 8%">
      <col style="width: 6%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= sort_link @search, :sku, Spree.t(:sku), { default_order: "desc" } %></th>
        <th><%= Spree.t(:status) %></th>
        <th></th>
        <th ><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
        <th class="text-left">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, {title: 'admin_products_listing_price_title'} %>
        </th>
        <th> Поставщик </th>
        <th>Закупочная цена</th>
        <th></th>
        <th></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody class="index-body-prod">
      <%= render :partial => "spree/admin/products/index_table", :locals => {:collection => @collection}%>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/products/update.js.erb
$(".index-body-prod").empty().append("<%= j(render :partial => 'spree/admin/products/index_table', :locals => {:collection => @collection})%>");